REPLIES = (
    (10, "gluh"),
    (10, "Gluh."),
    (5, "...gluh?"),
    (5, "g l u h"),
    (5, "gluh..."),
    (4, "gluh!"),
    (4, "gluh?"),
    (3, "GLUH!!"),
    (3, "gluh gluh"),
    (3, "\\*gluh noises\\*"),
    (3, "g-gluh...?"),
    (3, "gluh :3"),
    (3, "gluh 😀"),
    (3, "gluh ☹️"),
    (3, "gluh 🫤"),
    (3, "gluh 🫦"),
    (3, "gluh™"),
    (3, "gluh moment 🤯"),
    (3, "gluh 👍"),
    (3, "gluh 👎"),
    (3, "gl- gluh..."),
    (3, "gluh gluh, gluh!"),
    (3, "are we being Gluh"),
    (3, "like, gluh?"),
    (3, "With extra Gluh, please."),
    (3, "gluh ga gluh, gluh gluh."),
    (3, "gluh gluh, or gluh?"),
    (3, "gluh, gluh, and gluh!"),
    (3, "Gluh with a Capital 'G'."),
    (3, "gluhn't"),
    (3, "many such cases."),
    (3, "source: gluh"),
    (3, "Gluh Galunga"),
    (3, "watching Gluhgluhmelon rn sorry"),
    (3, '> Guhhhh, gluh.\n\\- gluh'),
    (3, "ERROR: gluh overflow"),
    (3, "1. gluh\n2. gluh\n3. ???\n4. gluh"),
    (3, "gluh quota exceeded"),
    (1, "gluh has reviewed your message and chosen violence"),
    (1, "gluh has been advised by legal counsel not to comment"),
    (1, "gluh? in this economy?"),
    (1, "gluh jumpscare (real)"),
    (1, "you have alerted the gluh"),
    (1, "gluh detected. activating neurotoxin."),
    (1, "I am in incredible pain. Uh, I mean... gluh"),
    (1, "gluh: command not found"),
    (1, "gluh returned exit code 137"),
    (1, "core dumped (gluh)"),
    (1, "gluh service unavailable due to gluh"),
    (0.5, "One day you will answer for your crimes. And God will not be as merciful as I am."),
    (0.5, "srry busy overthrowing lithuania. be bac l8r."),
    (0.5, "every copy of gluh is personalized"),
    (0.5, '\n'.join([
     "> No, go ahead, I've got this covered.",
     "> Yeah they still think it's a bot.",
     "> Of course I turned audio transcription off, why?",
     "> What?",
     "> Oh for fu-",
     "",
     "[END OF AUDIO LOG]",
     ])),
)


def messages() -> list[float]:
    return [i[1] for i in REPLIES]


def weights() -> list[str]:
    return [i[0] for i in REPLIES]
